version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env.local
    networks:
      - app-network

  celery_worker:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.celery
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env.local
    networks:
      - app-network

  celery_beat:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.celery
    command: celery -A task.celery_app beat --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env.local
    networks:
      - app-network

  flower:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.celery
    command: celery -A task.celery_app flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env.local
    depends_on:
      - celery_worker
    networks:
      - app-network

  # # 로컬 개발용 PostgreSQL
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: garmin_fit_bot
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - app-network

  # # 로컬 개발용 Redis
  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
# volumes:
#   postgres_data:
