version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly no --save
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis
    networks:
      - app-network

  celery_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    volumes:
      - .:/app
      - ./log:/app/log
    command: celery -A core.celery_app worker --loglevel=info
    depends_on:
      - redis
    networks:
      - app-network

  flower:
    profiles: ["optional"]
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    volumes:
      - .:/app
    command: celery -A core.celery_app flower --port=5555 --persistent=True --db=flower.db
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    external: true
