services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  celery_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    command: celery -A core.celery_app worker --loglevel=info --pool=solo -E
    networks:
      - app-network

  celery_beat:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    command: celery -A core.celery_app beat --loglevel=info
    depends_on:
      - celery_worker
    networks:
      - app-network

  flower:
    profiles: ["optional"]
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    command: celery -A core.celery_app flower --port=5555 --persistent=True --db=flower.db
    ports:
      - "5555:5555"
    depends_on:
      - celery_worker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
