version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

  celery_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    env_file:
      - .env
    networks:
      - app-network

  celery_beat:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    command: celery -A task.celery_app beat --loglevel=info
    env_file:
      - .env
    networks:
      - app-network

  flower:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    command: celery -A task.celery_app flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - celery_worker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
