services:
  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    volumes:
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
    depends_on:
      - node_exporter

networks:
  app-network:
    external: true
