services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: always
  
  celery_beat:
    profiles: ["production"]
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    volumes:
      - .:/app
    command: celery -A core.celery_app beat --loglevel=info
    networks:
      - app-network
    restart: always

  flower:
    profiles: ["optional"]
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    volumes:
      - .:/app
    command: celery -A core.celery_app flower --port=5555 --persistent=True --db=flower.db
    ports:
      - "5555:5555"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
