services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly no
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  celery_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    depends_on:
      - redis
    networks:
      - app-network

  celery_beat:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    command: celery -A core.celery_app beat --loglevel=info
    depends_on:
      - redis
    networks:
      - app-network

  flower:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    command: celery -A core.celery_app flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - celery_worker
      - redis
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
