"""update user information

Revision ID: b271bc4e34d6
Revises: ba155c6dc123
Create Date: 2025-02-23 21:22:12.429377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b271bc4e34d6'
down_revision: Union[str, None] = 'ba155c6dc123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('oauth_token', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('oauth_token_secret', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('domain', sa.String(length=255), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.drop_column('users', 'oauth2_token')
    op.drop_column('users', 'oauth1_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth1_token', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('oauth2_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.drop_column('users', 'domain')
    op.drop_column('users', 'oauth_token_secret')
    op.drop_column('users', 'oauth_token')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
