"""Update user oauth token column

Revision ID: ba155c6dc123
Revises: 
Create Date: 2025-02-22 20:41:35.877457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba155c6dc123'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth1_token', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('oauth2_token', sa.String(length=1024), nullable=True))
    op.drop_column('users', 'garmin_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('garmin_tokens', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('users', 'oauth2_token')
    op.drop_column('users', 'oauth1_token')
    # ### end Alembic commands ###
