"""Change TimeStampMixin

Revision ID: cccc2f8b049d
Revises: 9fb33a188d4a
Create Date: 2025-02-23 22:07:21.548986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cccc2f8b049d'
down_revision: Union[str, None] = '9fb33a188d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('analytics', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('analytics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('heart_rate_daily', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('heart_rate_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('sleep_sessions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('sleep_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('steps_daily', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('steps_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('stress_daily', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('stress_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.alter_column('stress_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('stress_daily', 'updated_at')
    op.alter_column('steps_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('steps_daily', 'updated_at')
    op.alter_column('sleep_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('sleep_sessions', 'updated_at')
    op.alter_column('heart_rate_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('heart_rate_daily', 'updated_at')
    op.alter_column('analytics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('analytics', 'updated_at')
    op.alter_column('activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('activities', 'updated_at')
    # ### end Alembic commands ###
