name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup deployment directory
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          # SSH 키 설정
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/ec2.key
          chmod 600 ~/.ssh/ec2.key
          
          # EC2에 필요한 디렉토리 생성 (없는 경우에만)
          ssh -i ~/.ssh/ec2.key -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST "[ ! -d /home/$EC2_USERNAME/app/backend ] && mkdir -p /home/$EC2_USERNAME/app/backend || echo 'Directory already exists'"

      - name: Copy backend files to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          # 백엔드 파일 전송
          rsync -avz -e "ssh -i ~/.ssh/ec2.key -o StrictHostKeyChecking=no" \
            --exclude='.venv' \
            --exclude='__pycache__' \
            --exclude='.pytest_cache' \
            --exclude='.mypy_cache' \
            --exclude='.ruff_cache' \
            --exclude='*.pyc' \
            backend/ $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/app/backend/

      - name: Deploy and restart services
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          ssh -i ~/.ssh/ec2.key -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST << 'EOF'
            cd /home/$EC2_USERNAME/app/backend
            
            # Docker 서비스 재시작
            docker compose down --rmi all --volumes --remove-orphans
            docker compose build
            docker compose up -d
            
            # 로그 확인
            docker compose logs -f
          EOF 